language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

#dependencies
install:
  - pip install -r requirements.txt
  - pip install -e
  #run tests
script:
  - pytest

branches:
  only:
    - master
